name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: inaechoi.dev/bookchat
          stage: main
          yaml: |
            name: bookchat
            app: web
            options:
              nodeversion: "18"
              docbase: dist
              build: npm run build
              spa: true
              indexpage: index.html
              buildenv:
                - name: VITE_BASE_URL
                  secret: VITE_BASE_URL
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
